name: "Build"
on:
  push:

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v2

    - name: "Compile and install dependencies"
      run: |
        brew install --build-from-source ./macos/sdl2.rb
